print("PROBLEMAS SOCIALES.")
print()
print("AREQUIPA - BULLING")
print("PUNO - POBREZA")
print("CUZCO - CONTAMINACION")
print()
n=str(input("Ingrese su nombre: "))
d=str(input("Ingrese su Departamento: "))
print()

if d=='AREQUIPA':
    print("SR. ",n," EL PROBLEMA SOCIAL QUE ACTUALMENTE ENFRENTA AREQUIPA ES EL BULLING")

else:
    if d=='PUNO':
        print("SR. ",n," EL PROBLEMA SOCIAL QUE ACTUALMENTE ENFRENTA PUNO ES LA POBREZA")
    else:
        if d=='CUZCO':
            print("SR. ",n," EL PROBLEMA SOCIAL QUE ACTUALMENTE ENFRENTA CUZCO ES LA CONTAMINACION")
